m1=matrix(c(1:9),nrow = 3,ncol=3)
m2=matrix(c(11:19),nrow = 3,ncol=3)
print("addition")
print(m1+m2)
print("subtraction")
print(m1-m2)
print("multiplication")
print(m1*m2)
print("divide")
print(m1/m2)